baseURL = "https://syst3matic.com"
languageCode = "en-us"
title = "syst3matic | blog"
theme = [ "hugo-chart", "hugo-kiera" ]


paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true


[params]
    tagline = "Syst3matic.com blog"
